version: '3.4'

services:
  accountdb:
     image : mongo

  assessmentdb:
     image : mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  
    ports:
      - "9200:9200"  # Elasticsearch HTTP API
      - "9300:9300"  # Transport port

  #Kibana Service for log visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Accounts/Account.API/Dockerfile

  assessment.api:
    image: ${DOCKER_REGISTRY-}assessmentapi
    build:
      context: .
      dockerfile: Services/Assessments/Assessment.API/Dockerfile





